# Generated by Django 3.0.5 on 2020-05-28 15:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=500)),
                ('titel', models.CharField(default='', max_length=500)),
                ('image', models.ImageField(default='', upload_to='article/images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='', max_length=1000)),
                ('product_des', ckeditor_uploader.fields.RichTextUploadingField()),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=70)),
                ('message', models.TextField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_model', models.CharField(default='', max_length=500)),
                ('product_brand', models.CharField(default='', max_length=500)),
                ('titel', models.CharField(default='', max_length=500)),
                ('image', models.ImageField(default='', upload_to='article/images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.CharField(default='', max_length=500, null='True')),
                ('description', models.TextField(default='', max_length=1000)),
                ('product_des', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_model', models.CharField(default='', max_length=500)),
                ('product_brand', models.CharField(default='', max_length=500)),
                ('titel', models.CharField(default='', max_length=500)),
                ('image', models.ImageField(default='', upload_to='article/images')),
                ('price', models.CharField(default='', max_length=500, null='True')),
                ('product_des', models.TextField(default='', max_length=1000)),
                ('product_detail', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('views', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(blank='False', max_length=254, null='True')),
            ],
        ),
    ]
