# Generated by Django 3.0.5 on 2020-05-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
